### ISSUE TITLE
Journal Page Suggested Improvements

### ISSUE THREAD

**Issue by connorch** [scrumptiousAmpersand/journey#19]
I have a couple suggestions for improvements:
- Add a "Today" Button that centers on the current date in the timeline.
- Add the day of the week to the dates in the  timeline (even just the letters would be good MTWTFSS).
- Add a margin-bottom to the bottom-most journal entry (Reflections) so that it's not crammed at the bottom of the page
- (Maybe) Instead of saying things like "Express gratitude" 3 times, possibly say that in the top placeholder, then in the other ones put examples in, like "I'm thankful for...", "I appreciate..."
## Context

Just some small suggestions to improve the UI and UX

**Comment by simeonlee** [comment]
Nice I like all of those. To be implemented soon.
